kind: Service
apiVersion: v1
metadata:
  name: balalncer-lb
  namespace: default
  annotations:
    service.beta.kubernetes.io/brightbox-load-balancer-healthcheck-request: /
spec:
  type: LoadBalancer
  selector:
    app: balalncer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: web